JobApplicationBoard/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JobApplicationBoard.Models;
using JobApplicationBoard.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace JobApplicationBoard.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;

        public AccountController(UserManager<AppUser> userManager, 
                                    SignInManager<AppUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("/account/login")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [Route("/account/login")]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);

                if (result.Succeeded)
                {
                    //If there is a redirect string in the urlpath it will redirect to the return url
                    if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }

                    // Redirects to home page
                    return RedirectToAction("Index", "Home");
                }


                ModelState.AddModelError(string.Empty, "Sorry! You entered a wrong email or password");
            }
            return View(model);
        }



        [HttpGet]
        [Route("/account/register")]
        public IActionResult Register()
        {
            return View();
        }


        
        [HttpPost]
        [Route("/account/register")]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser { UserName= model.Email, Email = model.Email};
                var result = await userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, isPersistent: true);
                    return RedirectToAction("Index", "Home");
                }

                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View();
        }

        [HttpPost]
        [Route("/account/logout")]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("/account/forgot-password")]
        public IActionResult ForgotPassword()
        {
            return View();
        }
    }
}

JobApplicationBoard/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JobApplicationBoard.Models;
using JobApplicationBoard.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JobApplicationBoard.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IJobRepo _jobRepo;
        private readonly IApplicantRepo _applicant;

        public AdminController(IJobRepo jobRepo, IApplicantRepo applicant)
        {
            _jobRepo = jobRepo;
            _applicant = applicant;
        }

        [Route("/admin")]
        public IActionResult Index()
        {
            return View();
        }

        
        [Route("/admin/all-applicants")]
        public IActionResult ViewApplicants()
        {
            return View();
        }

        
        [HttpGet]
        [Route("/admin/add-job")]
        public IActionResult CreateJob()
        {
            return View();
        }


        
        [HttpPost]
        [Route("/admin/add-job")]
        public IActionResult CreateJob(Job job)
        {
            Job newJob = _jobRepo. AddJob(job);
            return RedirectToAction("AllJobs");
        }


        [Route("/admin/all-jobs")]
        public IActionResult AllJobs()
        {
            var jobList = _jobRepo.GetJobs();
            ViewBag.Jobs = jobList;
            return View(jobList);
        }

        [Route("/admin/all-jobs/{jobId:int}")]
        public IActionResult JobDetails(int jobId)
        {
            var model = _jobRepo.GetJob(jobId);
            ViewBag.Job = model;
            return View();
        }


    }
}

JobApplicationBoard/Controllers/JobController.cs
using JobApplicationBoard.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobApplicationBoard.Controllers
{
    public class JobController : Controller
    {
        private readonly IJobRepo _jobRepo;

        public JobController(IJobRepo jobRepo)
        {
            _jobRepo = jobRepo;
        }

        [Route("/all-jobs")]
        public IActionResult Index()
        {
            var model = _jobRepo.GetJobs();
            ViewBag.Jobs = model;
            return View();
        }

        [Route("/all-jobs/{jobId:int}")]
        public IActionResult JobDetails(int jobId)
        {
            var model = _jobRepo.GetJob(jobId);
            ViewBag.Job = model;
            return View();
        }
    }
}

JobApplicationBoard/Views/Shared/_AccountView.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}


<section class="login-container justify-content-center d-flex py-5 px-2 px-md-5">
    <div class="col-12 col-sm-9 col-md-6 col-lg-5">
        <div class="card account-form-card w-100">
            <div class="card-body">
                <div class="d-flex align-items-center flex-column">
                    <div class="col-12 col-sm-10">
                        <h4 class="text-primary text-center">@ViewData["CardTitle"]</h4>
                        <hr class="d-block">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@RenderSection("Scripts", required: false)

JobApplicationBoard/Views/Shared/_Admin.cshtml
@{
    Layout = "_Layout.cshtml";
}


<section class="container">
    <ul class="nav nav-pills box-shadow">
        <li class="nav-item">
            <a class="nav-link active" asp-controller="Admin" asp-action="Index">Dashboard</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Jobs</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-controller="Admin" asp-action="AllJobs">All jobs</a>
                <a class="dropdown-item" asp-controller="Admin" asp-action="CreateJob">Create new job</a>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Applications</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">All applications</a>
                <a class="dropdown-item" href="#">Accepted applications</a>
                <a class="dropdown-item" href="#">Rejected applications</a>
            </div>
        </li>
    </ul>
    <div class="bg-light px-3 py-4">
        @RenderBody()
    </div>

    @RenderSection("Scripts", required: false)
</section>

JobApplicationBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkNation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-primary font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">WorkNation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="Index">Jobs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light bg-dark py-2">
        <div class="container text-center">
            &copy; 2020 - JobApplicationBoard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

JobApplicationBoard/Views/Shared/error404.cshtml
@{
    ViewData["Title"] = "Page not found";
}

<section class="py-4 d-flex align-items-center px-3 flex-column flex-lg-row banner bg-light">
    <div class="banner-img-container col-11 col-sm-10 px-4 col-md-8 mb-0">
        <img class="img-fluid" src="~/img/404_page_not_found_ (1).svg" alt="404 Image" />
    </div>
    <!--Banner content-->
    <div class="banner-content flex-column d-flex align-items-center">
        <h2 class="banner-heading mb-2 mb-lg-4 text-primary text-center">
            Sorry we couldn't find the page you were looking for!
        </h2>
        <a class="btn btn-sm btn-primary" asp-action="Index" asp-controller="Home">Return to homepage</a>
    </div>
    


</section>