JobApplicationBoard/Models/Applicant.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;
using Microsoft.EntityFrameworkCore;

namespace JobApplicationBoard.Models
{
    public enum Status
    {
        Pending,
        Accepted,
        Rejected
    }

    public class Applicant
    {
        [Key]
        public int ApplicantId { get; set; }

        [Required(ErrorMessage = "This field cannot be empty")]
        [MaxLength(25, ErrorMessage = "Cannot exceed 25 characters")]
        [Display(Name = "First name")]
        public string FirstName { get; set; }
        
        [Required(ErrorMessage = "This field cannot be empty")]
        [MaxLength(25, ErrorMessage = "Cannot exceed 25 characters")]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [EmailAddress(ErrorMessage = "Please enter a valid email")] 
        [Required(ErrorMessage = "You have to enter your email")]
        [Display(Name ="Email address")]
        public string EmailAddress { get; set; }

        [Url]
        [Required(ErrorMessage ="Please enter a valid url")]
        [Display(Name = "Link to portfolio")]
        public string PortfolioLink { get; set; }

        [Required]
        [Display(Name ="Level of Education")]
        public string LevelofEduction { get; set; }

        [Required(ErrorMessage = "Please upload your photo")]
        public string PhotoPath { get; set; }

        [Required(ErrorMessage ="Please upload your resume")]
        public string ResumePath { get; set; }

        [DefaultValue(Status.Pending)]
        [Display(Name = "Status")]
        public Status CurrentStatus { get; set; } = Status.Pending;

        [ForeignKey("JobId")]
        public int AppliedJob { get; set; }
        public EntityState State { get; internal set; }
    }
}

JobApplicationBoard/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JobApplicationBoard.Models;
using JobApplicationBoard.Repositories;
using JobApplicationBoard.Services;
using JobApplicationBoard.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace JobApplicationBoard.Controllers
{
    [Authorize]
    public class ApplicantController : Controller
    {
        private readonly IJobRepo _jobRepo;
        private readonly IApplicantRepo _applicantRepo;
        private readonly IUploadFileService uploadFileService;
        private readonly IEmailService emailService;

        public ApplicantController(
            IJobRepo jobRepo, 
            IApplicantRepo applicantRepo, 
            IUploadFileService uploadFileService,
            IEmailService emailService)
        {
            _jobRepo = jobRepo;
            _applicantRepo = applicantRepo;
            this.uploadFileService = uploadFileService;
            this.emailService = emailService;
        }

        [HttpGet]
        [Route("/apply/{jobId:int}")]
        public IActionResult Apply(int jobId)
        {
            Job job = _jobRepo.GetJob(jobId);
            ViewBag.Job = job;
            return View();
        }


        [HttpPost]
        [Route("/apply/{jobId:int}")]
        public IActionResult Apply(int jobId, ApplyFormModel formModel, IFormFile photo, IFormFile resume)
        {
            if (ModelState.IsValid)
            {
                string photoPath = "";
                if (photo != null)
                {
                    photoPath = uploadFileService.UploadFile(photo);
                }

                string resumePath = "";
                if (resume != null)
                {
                    resumePath = uploadFileService.UploadFile(resume);
                }

                Applicant newApplicant = new Applicant
                {
                    FirstName = formModel.FirstName,
                    LastName = formModel.LastName,
                    EmailAddress = formModel.EmailAddress,
                    PortfolioLink = formModel.PortfolioLink,
                    LevelofEduction = formModel.LevelofEduction,
                    PhotoPath = photoPath,
                    ResumePath = resumePath,
                    AppliedJob = jobId
                };

                _applicantRepo.EnrolApplicant(newApplicant);
                emailService.SendConfirmation(newApplicant.EmailAddress, newApplicant.FirstName);
                emailService.SendEmail("Entry", "devgbono@gmail.com", "Admin");
                return RedirectToAction("Index", "Job");
            }

            Job job = _jobRepo.GetJob(jobId);
            ViewBag.Job = job;

            return View();
        }


    }
}

JobApplicationBoard/Views/Applicant/Apply.cshtml
@model ApplyFormModel

@{
    var job = ViewBag.Job;
    ViewData["Title"] = "Apply as " + job.Title;
}


<section class="col-11 col-md-10 col-lg-8 mx-auto">
    <a href="/all-jobs/@job.JobId" class="mb-5">Back to details page</a>
    <form asp-controller="Applicant" asp-action="Apply" method="post" class="pt-2 pb-2 card px-3 px-sm-4 px-lg-6 my-4">
        <h3 class="text-primary text-center my-4">Apply as @job.Title</h3>
        <hr/>
        
        <section class="row">
            <div class="form-group col-sm-6">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group col-sm-6">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </section>

        <section class="row">
            <div class="form-group col-sm-6">
                <label asp-for="EmailAddress"></label>
                <input asp-for="EmailAddress" class="form-control" type="email" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group col-sm-6">
                <label asp-for="PortfolioLink"></label>
                <input asp-for="PortfolioLink" class="form-control" />
                <span asp-validation-for="PortfolioLink" class="text-danger"></span>
            </div>
        </section>

        <section class="row">
            <div class="form-group col-sm-6">
                <label asp-for="LevelofEduction"></label>
                <select asp-for="LevelofEduction" class="form-control">
                    <option value="College">College</option>
                    <option value="HND/OND">HND/OND</option>
                    <option value="Bachelors">Bachelors</option>
                    <option value="Masters">Masters</option>
                    <option value="Ph.D">Ph.D</option>
                </select>
                <span asp-validation-for="LevelofEduction" class="text-danger"></span>
            </div>
            <div class="form-group col-sm-6">
                <label for="photo">Passport Photo</label>
                <input name="photo" class="form-control-file" type="file" accept=".jpg, .png"/>
            </div>
        </section>

        <section class="row">
            <div class="form-group col-sm-6">
                <label for="resume">Resume</label>
                <input name="resume" class="form-control-file" type="file" accept=".pdf" />
            </div>
        </section>
        <div class="form-group my-3">
            <button type="submit" class="btn btn-primary btn-block">Submit Application</button>
            <p class="text-muted">
                <small>
                    By submitting this application, you are agreeing that the information supplied
                    by you is true.
                </small>
            </p>
        </div>
    </form>
        
</section>

JobApplicationBoard/Views/Applicant/Success.cshtml
@{
    ViewData["Title"] = "Success!";
}